#ifndef ParticleGun_h
#define ParticleGun_h


#include "G4Kernel/PrimaryGenerator.h"
#include "EventInfo/EventInfo.h"
#include "EventInfo/EventInfoContainer.h"
#include "G4ParticleGun.hh"
#include "G4GeneralParticleSource.hh"
#include "TRandom.h"
#include "TVector3.h"


class ParticleGun : public PrimaryGenerator 
{
   
  public:
    /** Constructor **/
    ParticleGun(std::string name);
    /** Destructor **/
    virtual ~ParticleGun();

    // The default behavior is that a single HepMC event generated by
    // GenerateHepMCEvent() will be converted to G4Event through HepMC2G4().
    virtual void GeneratePrimaryVertex(G4Event* anEvent) override;

    virtual StatusCode initialize() override;
    virtual StatusCode finalize() override;

    virtual PrimaryGenerator* copy() override;

  private:
    
    
    // We  have to take care for the position of primaries because
    // primary vertices outside the world voulme give rise to G4Execption.
    // If the default implementation is not adequate, an alternative
    // can be implemented in your own class.
    bool CheckVertexInsideWorld(const G4ThreeVector& pos) const;
    TVector3 RandomPos( float etamax );

    G4ParticleGun *m_gun;
    //G4GeneralParticleSource *m_gun;

    std::string m_particle;
    std::string m_eventKey;
    float m_energy;
    std::string m_energyDist;
    float m_sigma;
    float m_etamax;
    int m_evt;
    TRandom m_generator;

    std::vector<float> m_position;

};
#endif
