#!/usr/bin/env python3

from GaugiKernel          import LoggingLevel, Logger
import numpy as np
import argparse
import sys,os
pi = np.pi


mainLogger = Logger.getModuleLogger("job")
parser = argparse.ArgumentParser(description = '', add_help = False)
parser = argparse.ArgumentParser()


parser.add_argument('-i','--input-file', action='store', dest='input_file', required = False,
                    help = "The event input file generated by the Pythia event generator.")

parser.add_argument('-o','--outputfile', action='store', dest='output_file', required = False,
                    help = "The reconstructed event file generated by lzt/geant4 framework.")

parser.add_argument('--nov','--number-of-events', action='store', dest='number_of_events', required = False, type=int, default=-1,
                    help = "The number of events to apply the reconstruction.")

parser.add_argument('-l', '--output-level', action='store', dest='output_level', required = False, type=str, default='INFO',
                    help = "The output level messenger.")




if len(sys.argv)==1:
  parser.print_help()
  sys.exit(1)

args = parser.parse_args()

outputLevel = LoggingLevel.fromstring(args.output_level)

try:


  from GaugiKernel import ComponentAccumulator
  acc = ComponentAccumulator("ComponentAccumulator", args.output_file)


  from RootStreamBuilder import RootStreamAODReader, recordable

  aod = RootStreamAODReader("AODReader", 
                            InputFile            = args.input_file,
                            OutputLevel          = outputLevel,
                            OutputEventKey       = recordable("Events"),
                            OutputTruthKey       = recordable("Particles"),
                            OutputClusterKey     = recordable("Clusters"),
                            OutputRingerKey      = recordable("Rings"),
                            OutputElectronKey    = recordable("Electrons"),
                            OutputSeedsKey       = recordable("Seeds"),
                            NtupleName           = "CollectionTree",
                            )

  aod.merge(acc)
  
  from RootStreamBuilder import RootStreamNtupleMaker 
  ntuple = RootStreamNtupleMaker("NtupleMaker",
                                OutputLevel          = outputLevel,
                                InputEventKey        = recordable("Events"),
                                InputTruthKey        = recordable("Particles"),
                                InputClusterKey      = recordable("Clusters"),
                                InputRingerKey       = recordable("Rings"),
                                InputElectronKey     = recordable("Electrons"),
                                InputSeedsKey        = recordable("Seeds"),
                                OutputNtupleName     = "physics",
                                )
  
  acc+=ntuple
  
  acc.run(args.number_of_events)

  del acc
  sys.exit(0)
  
except  Exception as e:
  print(e)
  sys.exit(1)
