#!/usr/bin/env python3

from Gaugi.messenger      import LoggingLevel, Logger
from Gaugi                import GeV
from CaloClusterBuilder   import CaloClusterMaker
from CaloRingerBuilder    import CaloRingerMaker
from CaloCell.CaloDefs    import CaloSampling
from G4Kernel.utilities   import *
import numpy as np
import argparse
import sys,os


mainLogger = Logger.getModuleLogger("job")
parser = argparse.ArgumentParser(description = '', add_help = False)
parser = argparse.ArgumentParser()


parser.add_argument('-i','--inputFile', action='store', dest='inputFile', required = False,
                    help = "The event input file generated by the Pythia event generator.")

parser.add_argument('-o','--outputFile', action='store', dest='outputFile', required = False,
                    help = "The reconstructed event file generated by lzt/geant4 framework.")

parser.add_argument('-d', '--debug', action='store_true', dest='debug', required = False,
                    help = "In debug mode.")

parser.add_argument('--evt','--numberOfEvents', action='store', dest='numberOfEvents', required = False, type=int, default=-1,
                    help = "The number of events to apply the reconstruction.")

parser.add_argument('--outputLevel', action='store', dest='outputLevel', required = False, type=int, default=3,
                    help = "The output level messenger.")



pi = np.pi

if len(sys.argv)==1:
  parser.print_help()
  sys.exit(1)

args = parser.parse_args()


# Get all output names
if not '.root' in args.outputFile:
  args.outputFile+='.root'

outputLevel = 0 if args.debug else args.outputLevel

try:


  from GaugiKernel import ComponentAccumulator
  acc = ComponentAccumulator("ComponentAccumulator", args.outputFile)


  from RootStreamBuilder import RootStreamESDReader
  ESD = RootStreamESDReader("ESDReader", 
                            InputFile       = args.inputFile,
                            CellsKey        = recordable("Cells"),
                            EventKey        = recordable("EventInfo"),
                            TruthKey        = recordable("Particles"),
                            NtupleName      = "CollectionTree",
                          )
  ESD.merge(acc)


  # build cluster for all seeds
  cluster = CaloClusterMaker( "CaloClusterMaker",
                              CellsKey        = recordable("Cells"),
                              EventKey        = recordable("EventInfo"),
                              ClusterKey      = recordable("Clusters"),
                              TruthKey        = recordable("Particles"),
                              EtaWindow       = 0.4,
                              PhiWindow       = 0.4,
                              MinCenterEnergy = 0.1*GeV, # 15GeV in the EM core 
                              HistogramPath   = "Expert/Clusters",
                              OutputLevel     = outputLevel )

  ringer = CaloRingerMaker(   "CaloRingerMaker",
                              RingerKey     = recordable("Rings"),
                              ClusterKey    = recordable("Clusters"),
                              DeltaEtaRings = [0.025,0.00325, 0.025, 0.050, 0.1, 0.1, 0.2 ],
                              DeltaPhiRings = [pi/32, pi/32, pi/128, pi/128, pi/128, pi/32, pi/32, pi/32],
                              NRings        = [8, 64, 8, 8, 4, 4, 4],
                              LayerRings = [
                                [CaloSampling.PSB, CaloSampling.PSE],
                                [CaloSampling.EMB1, CaloSampling.EMEC1],
                                [CaloSampling.EMB2, CaloSampling.EMEC2],
                                [CaloSampling.EMB3, CaloSampling.EMEC3],
                                [CaloSampling.HEC1, CaloSampling.TileCal1, CaloSampling.TileExt1],
                                [CaloSampling.HEC2, CaloSampling.TileCal2, CaloSampling.TileExt2],
                                [CaloSampling.HEC3, CaloSampling.TileCal3, CaloSampling.TileExt3],
                              ],
                              HistogramPath = "Expert/Rings",
                              OutputLevel   = outputLevel)
 

  from RootStreamBuilder import RootStreamAODMaker
  AOD = RootStreamAODMaker( "RootStreamAODMaker",
                          CellsKey        = recordable("Cells"),
                          EventKey        = recordable("EventInfo"),
                          TruthKey        = recordable("Particles"),
                          RingerKey       = recordable("Rings"),
                          ClusterKey      = recordable("Clusters"),
                          DumpCells       = False,
                          OutputLevel     = outputLevel)
      
  # sequence
  acc+= cluster
  acc+= ringer
  acc+= AOD

  acc.run(args.numberOfEvents)

  sys.exit(0)
  
except  Exception as e:
  print(e)
  sys.exit(1)
