#!/usr/bin/env python3

from GaugiKernel.constants import *
from GaugiKernel           import LoggingLevel, Logger
from G4Kernel              import *
from CaloCell.CaloDefs     import CaloSampling
from RootStreamBuilder     import recordable
import numpy as np
import argparse
import sys,os,gc


mainLogger = Logger.getModuleLogger("job")
parser = argparse.ArgumentParser(description = '', add_help = False)
parser = argparse.ArgumentParser()


parser.add_argument('-i','--inputFile', action='store', dest='inputFile', required = True,
                    help = "The event input file generated by the Pythia event generator.")

parser.add_argument('-o','--outputFile', action='store', dest='outputFile', required = True,
                    help = "The reconstructed event file generated by lzt/geant4 framework.")

parser.add_argument('-nt','--numberOfThreads', action='store', dest='numberOfThreads', required = False, type=int, default=1,
                    help = "The number of threads")

parser.add_argument('--evt','--numberOfEvents', action='store', dest='numberOfEvents', required = False, type=int, default=None,
                    help = "The number of events to apply the reconstruction.")

parser.add_argument('--visualization', action='store_true', dest='visualization', required = False,
                    help = "Run with Qt interface.")

parser.add_argument('--enableMagneticField', action='store_true', dest='enableMagneticField',required = False, 
                    help = "Enable the magnetic field.")

parser.add_argument('--saveAllHits', action='store_true', dest='saveAllHits', required = False, 
                    help = "Save all detector hits.")

parser.add_argument('-t','--timeout', action='store', dest='timeout', required = False, type=int, default=120,
                    help = "Event timeout in minutes")

parser.add_argument('-l', '--outputLevel', action='store', dest='outputLevel', required = False, type=str, default='INFO',
                    help = "The output level messenger.")



if len(sys.argv)==1:
  parser.print_help()
  sys.exit(1)

args = parser.parse_args()

outputLevel = LoggingLevel.fromstring(args.outputLevel)

try:

  from ATLAS import ATLASConstruction as ATLAS

  # Build the ATLAS detector
  detector = ATLAS(
                   UseMagneticField = args.enableMagneticField, # Force to be false since the mag field it is not working yet
                   CutOnPhi = False,
                   )

  acc = ComponentAccumulator("ComponentAccumulator", detector,
                              RunVis=args.visualization,
                              NumberOfThreads = args.numberOfThreads,
                              Seed = 512, # fixed seed since pythia will be used. The random must be in the pythia generation
                              OutputFile = args.outputFile,
                              Timeout = args.timeout * MINUTES )
  


  gun = EventReader( "EventReader",
                     EventKey   = recordable("EventInfo"),
                     TruthKey   = recordable("Particles"),
                     FileName   = args.inputFile,
                     BunchDuration = 25.0,#ns
                     )

  from CaloCellBuilder import CaloHitBuilder
  calorimeter = CaloHitBuilder("CaloHitBuilder",
                                HistogramPath = "Expert/Hits",
                                OutputLevel   = outputLevel,
                                )

  gun.merge(acc)
  calorimeter.merge(acc)

  OutputHitsKey   = recordable("Hits")
  OutputEventKey  = recordable("EventInfo")

  from RootStreamBuilder import RootStreamHITMaker, recordable

  HIT = RootStreamHITMaker( "RootStreamHITMaker",
                             # input from context
                             InputHitsKey    = OutputHitsKey,
                             InputEventKey   = OutputEventKey,
                             InputTruthKey   = recordable("Particles"),
                             # output to file
                             OutputHitsKey   = recordable("Hits"),
                             OutputEventKey  = recordable("EventInfo"),
                             OutputTruthKey  = recordable("Particles"),
                             # special parameters
                             EtaWindow       = 0.6,
                             PhiWindow       = 0.6,
                             OnlyRoI         = not args.saveAllHits,
                             OutputLevel     = outputLevel)

  acc += HIT
  
  acc.run(args.numberOfEvents)
  
  if args.visualization:
      input("Press Enter to quit...")

  
  #del acc # remove all instances
  #gc.collect() # make sure everything was removed
  sys.exit(0)
  
except  Exception as e:
  print(e)
  sys.exit(1)
